version: "3"
services:
    postgres:
        image: postgres:latest
        restart: always
        ports:
            - "15432:5432"
        environment:
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=myuserpass
            - POSTGRES_DB=mydb
        volumes:
            - "./data/db/postgres:/var/lib/postgresql"
