version: "3"
services:
    mysql:
        image: mysql:5.7
        command: 
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
        restart: always
        ports:
            - "13306:3306"
        environment:
            - MYSQL_DATABASE=mydb
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=myuserpass
        volumes:
            - "./data/db/mysql:/var/lib/mysql" 
